#
# Updated: Woo-il Song, 2007
# Updated: Byung-Hee HWANG <soyeomul@doraji.xyz>, 2018-06-29
<p>버그 추적 시스템(BTS) 문서들:

<ul>
  <li><a href="./">버그 추적 시스템(BTS) 메인 차례 페이지.</a>
  <li><a href="Reporting">버그 보고서 제출 방법 소개.</a>
  <li><a href="Access">버그 추적 시스템(BTS) 로그에 접근하기.</a>
  <li><a href="Developer">개발자를 위한 도움말 -- 버그 추적 시스템(BTS).</a>
  <li><a href="server-control">전자메일로 버그 보고서를 제어하기 위한 방법.</a>
  <li><a href="server-refcard">메일서버의 참조 카드.</a>
  <li><a href="server-request">전자메일로 버그 보고서의 정보 요청하기.</a>
#  <li><a href="db/ix/full.html">버그 보고서의 전체 목록.</a>
#  <li><a href="db/ix/packages.html">버그 보고서가 있는 패키지 목록.</a>
#  <li><a href="db/ix/maintainers.html">버그 보고서가 있는 패키지의 관리자 목록.</a>
</ul>

